version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - noticias_pg_data:/bitnami/postgresql
    ports:
      - "5200:5432"
volumes:
  noticias_pg_data: